export const ADD_TASK = 'ITEM/ADD_TASK';
export const REMOVE_TASK = 'ITEM/REMOVE_TASK';
export const CHANGE_TASK = 'ITEM/CHANGE_TASK';
export const COMPLETED_TASK = 'ITEM/COMPLETED_TASK';
export const ALL_COMPLETED_TASK = 'ITEM/ALL_COMPLETED_TASK';
export const REMOVE_COMPLETED_TASK = 'ITEM/REMOVE_COMPLETED_TASK';